spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 150MB
      max-request-size: 150MB


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

http:
  port: 8085 # http服务端口

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 18144000 #JWT的超期限时间(30*60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
      orderId: "portal:orderId:"
      memberTelephone: "portal:memberTelephone:"
      waitPay: "portal:order:waitPay:"
      otoWaitPay: "portal:order:otoWaitPay:"
    expire:
      authCode: 90 # 验证码超期时间
      member: 604800 # redis用户有效时间(7天)

# redisson 单节点模式
redisson:
  password: mmt123 # Redis服务器连接密码（默认为空
  singleServerConfig:
    address: localhost:6379
    database: 0 # Redis数据库索引（默认为0）


# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue



alicloud:
  regionId: cn-hangzhou
  prBasic: 91xiaoxiangzu
  accessKeyId: LTAIdF00HsZdZi3k
  accessKeySecret: NBb4yxDYb5El4vMyRkGxIlWv0crwvA


logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.xxz.rent: debug