server:
  port: 8443 #开发环境会开启https
  ssl:
    key-store: keystore.p12
    key-alias: tomcat
    key-store-password: 123456
    key-store-type: PKCS12



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xxz?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mmt123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid


  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: mmt123 # Redis服务器连接密码（默认为空
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000ms # 连接超时时间（毫秒）


  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: xxz
    username: mmt
    password: mmt888888
    publisher-confirms: true #如果对异步消息需要回调必须设置为true



aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessendPoint: xiaoxiangzu.oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAIdF00HsZdZi3k
    accessKeySecret: NBb4yxDYb5El4vMyRkGxIlWv0crwvA
    bucketName: xiaoxiangzu
    policy:
      expire: 300
    maxSize: 10
    callback: http://localhost:8080/aliyun/oss/callback
    dir:
      prefix: images/


#alipay:
#  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjiYuT3rMbSRUiLHLb4F6hXRHdArgRAvNTmXS9DvWKe6S6Gu5tI1s4ybtsDf+NJZ12rXovqig3exJtvOQeqLhoM4WwQ5ICbLjJUaBdHUbjbDWqpOVpxBCe/jLvVGvuecVgjWO61zaruAGfN+iEb8RfC39KM4Z3A3OSOs02+BTAD9LkwTT8vzhjcaj1YU+rAWdAEqGO8/X4D/vcuxSXHGRElE/Jh9/SGTk5SHieQmA/1icO/QE1Cf8pUvHS0tA3M9Iux3I/x99cKENdZX8AQxK4BxoMu3Os2jkKedygxU2FUfyWLQVuIr6021j/kMRHrvLF3i5hiclJib7WqRTt6gWhQIDAQAB
#  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCOJi5PesxtJFSIsctvgXqFdEd0CuBEC81OZdL0O9Yp7pLoa7m0jWzjJu2wN/40lnXatei+qKDd7Em285B6ouGgzhbBDkgJsuMlRoF0dRuNsNaqk5WnEEJ7+Mu9Ua+55xWCNY7rXNqu4AZ836IRvxF8Lf0ozhncDc5I6zTb4FMAP0uTBNPy/OGNxqPVhT6sBZ0ASoY7z9fgP+9y7FJccZESUT8mH39IZOTlIeJ5CYD/WJw79ATUJ/ylS8dLS0Dcz0i7Hcj/H31woQ11lfwBDErgHGgy7c6zaOQp53KDFTYVR/JYtBW4ivrTbWP+QxEeu8sXeLmGJyUmJvtapFO3qBaFAgMBAAECggEAcGfg1xjT7rp73lw58sMAj+eTWUAAd86dWxFJ77ghcqclpIULJKtxH275JhAhBJS2PWz7z0ipbNQctn+EEHYc1XwioicY8BJ1bFSEqgKw9yqPlfN+s803xbDH671cqDUD3SNdEOEsTHz6pGRzVHUy7m+vcUUJTenc5eyYsAaDm/1DotUpWjeIdwW3sIHdJxBvqHz3l+khTLoMji9iIXg0+ZKsYu4XnhMUGWS98YIiiIJM6JpmFnTFFGYaSFlsuQxvGtYznxcfqPRywDs4Yqrg+yQbDR3Dhj0839lFo7jK0UgNeawr1UFCOolxdINvh/+n4lu5HzB7+6XqAc8MmqXuAQKBgQC/KJosoi04jvUf4TORfDlM7bk9FOFHwWHNAD1ijZ4Vd6qyyYWr0BXhH0g4/qmNIooxFOHv35qBKeMjOaHpK/DHtoQYL0vUJNszl4WhEA6TFvDZKH1S4uk5BAYKKRkUu8SFpBA98bWWPPsZV6YQdfP/Oc7FjNRMkAz4ROFwV2Y22QKBgQC+Xc5qspNDSEClwFg/hMZF1SwyhgJvSpkW8m1Bctr1oMcU/RKfAizH9Z+xHRxvbGRnThQkretSLfn++AkH7jxHwmuer69PgoZn35NbB+VHDLiwEnUkxnUP7ygeTxXnSXRp7koHqnlHNO++IjPdHYWQa5iWVyv72xdgOy4R4XhJjQKBgQCr+AzrBmMENKeUrHZF9ale6aXxq20XroMbd5HBrYF/8o3gFadpb+OfCRNiIsfJrj7/9LdlopVOia5LLDfamqscH7gqQbJIAXgpq7CNuvJBpSu7UM+d14DUyCfe0CY+HsWnLHdoIqCnreh/XfiJanO9MfYwhoce8aCZYO4msJnF0QKBgCTMw4Nyw+8Ev6KLHUQiKaYEQIf/yeazuAZslNxLFLLZAsM27OuaIwgAnn9BjmanwH0L5e71RAFd6+7zCePjlPmWRvGlKrGnHM5ltPmq/BKRDf7Tgpu6VZTf+ZRqW2SbmYqEywDSXqF6RUIvIHGFLHWvpw6hCVqljs5GgnBocrVdAoGBAIz6pjtUYAsKN0HjXSPm3qOSt+NMNYKWGdJVGnXKnaACvRWxIzgSWJwVquICkvZpTj42JVvHYlT3SV0+AX8Ra3HRpamw7l1OeNkouJ2phvzOQg1sIk6Sn/F9f9+8mXDclN/daAjs6fZNYuMiNEEaMCDTNyIkJKrL++w1azWZm4Hv
#  appId: 2016091400510876

#wechat:
#  appId: wx13e6963ce014537b
#  mchId: 1540260361
#  privateKey: 5bb08b912bfdf2a1d43c08ae16222aa0
#  url: https://api.mch.weixin.qq.com/sandboxnew/pay/unifiedorder
#  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
#  appSecret: 03d2f1e9520432302086ae60ddaa01c0
#  userInfoUrl: https://api.weixin.qq.com/sns/userinfo

alipay:
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA1oRPk/N0Hzt6oTmnGRQWUdRkgrDamL1ACzZWC5y+d1GiOb4pWnpBYnHgh7ty8Y29uWsPILCE8dy+391oMi7WYq1OEmO1ZRzleuZoiNUDQmoHSLL6aKREB9DM/jNPYTEDbEaYoTaO8o15z2pqyYJimR3ahu38mcdhbsim9EFq7L6Of30uv4PMfccg9jPNm2LUXz/5eakfxWP4ZJKot4KMQi2zer1XeMH+XDVFpp56+5cQkgwbwILEXhN416nrlNPQT2TBApp2jnrLCnJ4HBAoLx16Ta1It8LFpW6V1256cbJbBXehstNJtEL/XsxMBiHxiCNbJ4xF3/jD3gq25zPlCQIDAQAB
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDWhE+T83QfO3qhOacZFBZR1GSCsNqYvUALNlYLnL53UaI5vilaekFiceCHu3Lxjb25aw8gsITx3L7f3WgyLtZirU4SY7VlHOV65miI1QNCagdIsvpopEQH0Mz+M09hMQNsRpihNo7yjXnPamrJgmKZHdqG7fyZx2FuyKb0QWrsvo5/fS6/g8x9xyD2M82bYtRfP/l5qR/FY/hkkqi3goxCLbN6vVd4wf5cNUWmnnr7lxCSDBvAgsReE3jXqeuU09BPZMECmnaOessKcngcECgvHXpNrUi3wsWlbpXXbnpxslsFd6Gy00m0Qv9ezEwGIfGII1snjEXf+MPeCrbnM+UJAgMBAAECggEAQejVKngarZ3wx6iXFrV9Rhcj6qO8BkHfc5J2TYsTWkXSujsbKZl2jXC/s/R8FIugR2AFfd2+ezF/0/iLEyAg7qCg5DWOfkqql2BDrgcEwVsiccvL9GrEHEKjOVc6hHoyuwnVy3Kf6RZe3sOrm85bzP/HLL3iZr1Dym4MHfAbkjFKOTQYYQITmOKtrnx/WqQ1lV0IeyxC5csSLM3qt5gcb7XYaK6F/Psniuq9uXv6J3XZvkAQnJ4EEkQwGqUe7dPAt76Y17eQB/4WgkgthSb6BWYyMO5OtrtKjdTBuMQq9+a6kZjYYmm4xOnz/718DedeBAGOXq/s2/QRtc42FC0CgQKBgQDwn2EQdaG/N+CLpjOJ+uuNtlmwgBaQxytL3fqgmWi1KHk7gPE+/CX3K9k0/XM5XNGCwC3qP1aFK2Z28JG4+/8MJ6nEa7QO+W66WWLTP/rPbrsuzz8N66kW3HkWzsfobWD08VPq2TfoqsvfcItkdcIZJqzXwwgt5xVlnQRjaBU6jQKBgQDkOdaHl/a95yFjj/Kpprn+bUPiWThEHAw6Tw9Xe1ThriuRUePpjfyx+1csx8L1f6YcXOFcXbGt9G1OzyBqf8bZxk1wdOycrf1WJ11aCUlUhpxgJtpzsJ0S2g4DfVZGZVOA0uap/kwBjNaD/X2tjA8kAkTzeOEcmfuAtZVhZneTbQKBgQCexNs8DBIU5R7BpoG9WpaQpDCb+HhrQS/9WFPmIjNnzXPo4lTMdX3rkMA6ab3crLUFbB8fwHkrV469jlDo2UXZ1FX9Z/+gHc+FIDPIJiAtPOg/o7n8SnIAxqsTdI+NepaOKKpxfLCaUhBBt7YSLG1NQSqtF2BPQXnp2Wgq22OehQKBgQDTlWN0NchE6oCj4xIfgjiwze+/auOlETOs4xrgCbD5wRUXFoprPn1lLBT3qQLvwrXnWZx8m0hcc1zbUV9GHMvnndaxSVULNKrHMptzG2Tmfh1/bsXbt4MHtSyEw7A2dz3hEqVSODWSwlUl7N6VBGINCiWOaySX9ZGbE703nV2CSQKBgAKVnDkt/mzJZdX9BHozd49wUFK8QegX7XdupDri0JU55zjgZzfltEnttlX2dVpaJG6u8Nd643o7BDEzSyVJtzc45pdysuJdjZ5g4f7Fif1wcKFBZfhKCXqpxAioFqW8wuae2A1WimrMBmGN1T/YdzFZUEAyUl5/xA/jm3qSyDRm
  appId: 2018052360203156

wechat:
  appId: wx13e6963ce014537b
  mchId: 1540260361
  privateKey: 5bb08b912bfdf2a1d43c08ae16222aa0
  url: https://api.mch.weixin.qq.com/pay/unifiedorder
  appSecret: 03d2f1e9520432302086ae60ddaa01c0
  accessTokenUrl: https://api.weixin.qq.com/sns/oauth2/access_token
  userInfoUrl: https://api.weixin.qq.com/sns/userinfo


# 日志配置
logging:
  level:
    org.springframework.data.mongodb.core: debug
    com.macro.mall.mapper: debug
    com.macro.mall.portal.dao: debug

