spring:
  profiles:
    active: dev #默认为开发环境


mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml


jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mySecret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24)
  tokenHead: Bearer  #JWT负载中拿到开头

# 自定义redis key
redis:
  key:
    prefix:
      adminUsername: "rent-admin:adminUsername:"
      adminPermission: "rent-admin:adminPermission:"
    expire:
      admin: 86400 # redis用户有效时间

aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: LTAIdF00HsZdZi3k
    accessKeySecret: NBb4yxDYb5El4vMyRkGxIlWv0crwvA
    bucketName: xiaoxiangzu
    policy:
      expire: 300
    maxSize: 10
    callback: http://localhost:8080/aliyun/oss/callback
    dir:
      prefix: images/



logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.xxz.rent: debug
#  file: demo_log.log #配置日志生成路径
#  path: /var/logs #配置日志文件名称
